[project]
name = "cat-dog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckduckgo-search>=7.4.2",
    "ipykernel>=6.29.5",
    "label-studio>=1.16.0",
    "requests>=2.32.3",
]
